version: "3"
services:
  app:
    build: .
    command: "streamlit run Home.py"
    ports:
      - "8501:8501"
    depends_on:
      - ts_database
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: