version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run Home.py"
    ports:
      - "8501:8501"
    #volumes:
    #  - "./src:/usr/src/app/src"
  database:
    image: "mongo"
    environement:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27020:27017"
volumes:
  mongodb-data:
