version: "3"

services:
  frontend:
    build: ./
    command: "python3 -m streamlit run app/Home.py"
    ports:
      - "8501:8501"
    depends_on:
      - backend

  backend:
    build: ./
    command: "python3 -m api.main"
    ports:
      - "8502:8502"
    depends_on:
      - mongodb

  mongodb:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27018:27017"


volumes:
  mongodb-data:

